version: '3.8'

services:
  web:
    container_name: auth
    image: "registry.gitlab.com/i2dru/auth"
    ports:
      - "8082:8082"
    networks:
      - local
      - bridge
    environment:
      - KEYCLOAK_URL=$KEYCLOAK_URL
      - KEYCLOAK_OAUTH_URI=$KEYCLOAK_OAUTH_URI
networks:
  bridge:
    name: bridge
    external: true
  local:
    name: local
    external: true