version: '3.8'

services:
  web:
    container_name: auth
    image: "registry.gitlab.com/i2dru/auth"
    ports:
      - "8082:8082"
    networks:
      - local
      - auth-network
    environment:
      - KEYCLOAK_URL=$KEYCLOAK_URL
      - KEYCLOAK_OAUTH_URI=$KEYCLOAK_OAUTH_URI
networks:
  auth-network:
    driver: bridge
  local:
    name: local
    external: true