version: '3.8'

services:
  web:
    container_name: router
    image: "registry.gitlab.com/mrcod/router"
    ports:
      - "8281:80"
    networks:
      - local
      - mysql
    environment:
      - DBPORT=$DBPORT
      - DBHOST=$DBHOST
      - DBNAME=$DBNAME
      - DBUSERNAME=$DBUSERNAME
      - DBPASSWORD=$DBPASSWORD
      - PORT=$PORT
networks:
  mysql:
    name: mysql
    external: true
  local:
    name: local
    external: true
