version: '3'

services:
  web:
    container_name: restf
    image: "registry.gitlab.com/fggnb45598/restfront:latest"
    ports:
      - "9001:80"
networks:
  default:
    external:           
      name: local
