version: '3'

services:
  web:
    container_name: restf
    image: "docker.pkg.github.com/dschek/rest/front:latest"
    ports:
      - "9001:80"
networks:
  default:
    external:           
      name: local