version: '3.8'

services:
  web:
    container_name: restb
    image: "docker.pkg.github.com/dschek/rest/back:latest"
    ports:
      - "8080:8080"
    networks:
      - local
      - mysql
    environment:
      - DBPORT=$DBPORT
      - DBHOST=$DBHOST
      - DBNAME=$DBNAME
      - DBUSERNAME=$DBUSERNAME
      - DBPASSWORD=$DBPASSWORD
      - PORT=$PORT
networks:
  mysql:
    name: mysql
    external: true
  local:        
    name: local   
    external: true     
