version: '3.8'

services:
  web:
    container_name: restb
    image: "docker.pkg.github.com/dschek/restcms/restcms:latest"
    ports:
      - "8080:8080"
    networks:
      - restb
      - mongodb
    environment:
      - DBPORT=$DBPORT
      - DBHOST=$DBHOST
      - DBNAME=$DBNAME
      - DBUSERNAME=$DBUSERNAME
      - DBPASSWORD=$DBPASSWORD
      - PORT=$PORT
networks:
  network1:
    name: mongodb
    external: true
  default:
    external:           
      name: local