version: '3.8'

services:
  web:
    container_name: restb
    image: "docker.pkg.github.com/dschek/restcms/restcms:latest"
    ports:
      - "8080:8080"
    networks:
      - restb
      - mysql
networks:
  restb: {}
  mysql:
    external: true
