services:
  web:
    container_name: tydip
    image: "registry.gitlab.com/fggnb45598/post:latest"
    ports:
      - "8080:8081"
    networks:
      - local
      - postgres
    environment:
      - DBPORT=$DBPORT
      - DBHOST=$DBHOST
      - DBNAME=$DBNAME
      - DBUSERNAME=$DBUSERNAME
      - DBPASSWORD=$DBPASSWORD
      - PORT=$PORT
networks:
  mysql:
    name: postgres
    external: true
  local:
    name: local
    external: true
