version: '3.8'

services:
  web:
    container_name: keycloak
    image: "registry.gitlab.com/fggnb45598/keycloak:latest"
    command: start
    ports:
      - "8433:8433"
      - "8180:8080"
    networks:
      - local
      - postgres
    environment:
      KC_DB: postgres
      KC_PROXY_HEADERS: xforwarded
      KC_FEATURES: hostname[:v2]
      KC_PROXY_PROTOCOL_ENABLED: true
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_DB_URL: $DB_URL
      KC_DB_USERNAME: $DB_USER
      KC_DB_PASSWORD: $DB_PASSWORD
      KEYCLOAK_ADMIN: $USERNAME
      KEYCLOAK_ADMIN_PASSWORD: $PASSWORD
      KC_HOSTNAME: $ADMIN_URL
#      KC_HTTPS_PORT: 8180
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_DEBUG: true
    restart: unless-stopped
networks:
  local:
    external: true
    name: local
    attachable: true
  postgres:
    name: postgres
    external: true