version: '3.8'

services:
  web:
    container_name: keycloak
    image: "mirror.gcr.io/keycloak/keycloak:20.0.2"
    command: start
    ports:
      - "8433:8433"
    networks:
      - local
      - postgres
    environment:
      KC_DB: postgres
#      KC_DB_SCHEMA: public
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY_HEADERS: 'xforwarded'
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_PROXY_PROTOCOL_ENABLED: 'true'
      KC_HOSTNAME_V2: 'true'
      #      KC_PROXY: edge
#      proxy: something
      KC_DB_URL: $DB_URL
      KC_DB_USERNAME: $DB_USER
      KC_DB_PASSWORD: $DB_PASSWORD
      KEYCLOAK_ADMIN: $USERNAME
      KEYCLOAK_ADMIN_PASSWORD: $PASSWORD
      KC_HOSTNAME: $HOSTNAME
      KC_HOSTNAME_ADMIN: $HOSTNAME
    #    healthcheck:
#      test:
#        - "CMD-SHELL"
#        - |
#          exec 3<>/dev/tcp/localhost/9000 &&
#          echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 &&
#          cat <&3 | tee /tmp/healthcheck.log | grep -q '200 OK'
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 90s
    restart: unless-stopped
networks:
  local:
    external: true
    name: local
    attachable: true
  postgres:
    name: postgres
    external: true