version: '3.8'

services:
  web:
    container_name: keycloak
    image: "mirror.gcr.io/keycloak/keycloak:20.0.2"
    command: start
    ports:
      - "8433:8433"
      - "8180:8080"
    networks:
      - local
      - postgres
    environment:
      KC_DB: postgres
      KC_HEALTH_ENABLED: true
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_V2: true
      PROXY_ADDRESS_FORWARDING: true
      KC_PROXY_PROTOCOL_ENABLED: true
      KC_DB_URL: $DB_URL
      KC_DB_USERNAME: $DB_USER
      KC_DB_PASSWORD: $DB_PASSWORD
      KEYCLOAK_ADMIN: $USERNAME
      KEYCLOAK_ADMIN_PASSWORD: $PASSWORD
      KC_HOSTNAME: $HOSTNAME
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_ADMIN: $ADMIN_URL
    restart: unless-stopped
networks:
  local:
    external: true
    name: local
    attachable: true
  postgres:
    name: postgres
    external: true