version: '3.8'

services:
  web:
    container_name: keycloak
    image: "registry.gitlab.com/fggnb45598/keycloak:latest"
#    command: start
    ports:
      - "8443:8443"
      - "8080:8080"
    networks:
      - local
      - postgres
    environment:
      KC_DB: postgres
      KC_PROXY_HEADERS: xforwarded
      KC_FEATURES: hostname[:v2]
      KC_PROXY_PROTOCOL_ENABLED: true
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_DB_URL: $DB_URL
      KC_DB_USERNAME: $DB_USER
      KC_DB_PASSWORD: $DB_PASSWORD
      KEYCLOAK_ADMIN: $USERNAME
      KEYCLOAK_ADMIN_PASSWORD: $PASSWORD
      KC_HOSTNAME: $ADMIN_URL
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY: none
      KC_HOSTNAME_STRICT: false
    command: [
      "start", \
      "--hostname-strict-https=false", \
      "--hostname-strict=false", \
      "--http-enabled=true", "--https-port=0", \
      "--spi-x509cert-lookup-nginx-ssl-client-cert=SSL_CLIENT_CERT", \
      "--spi-x509cert-lookup-nginx-ssl-cert-chain-prefix=CERT_CHAIN", \
      "--spi-x509cert-lookup-nginx-certificate-chain-length=10"
    ]
    restart: unless-stopped
networks:
  local:
    external: true
    name: local
    attachable: true
  postgres:
    name: postgres
    external: true