services:
  back:
    container_name: back_mrcod
    image: "registry.gitlab.com/mrcod/back:latest"
    networks:
      - local
      - db
    environment:
      - HTTP_ADDR=:8080
      - LOG_LEVEL=info
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
      - SESSION_SECRET=$SESSION_SECRET
      - SESSION_COOKIE_SECURE=true
      - CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS
      - DEFAULT_TOKEN_DOMAIN_SUFFIX=mrcod1.ru
      - INTERNAL_DOMAIN_SUFFIX=domains.nozi.io
      - INFRA_API_BASE_URL=http://infra:8082
      - PAYMENTS_API_BASE_URL=https://api.payment-provider.com/api/v1
      - PAYMENTS_CHECKOUT_BASE_URL=$PAYMENTS_CHECKOUT_BASE_URL
      - PAYMENTS_KEY=$PAYMENTS_KEY
      - TARIFF_SYNC_TOKEN=$TARIFF_SYNC_TOKEN
      - WORKER_TIMEOUT=12s
      - INFRA_SHARED_TOKEN=$INFRA_SHARED_TOKEN
networks:
  db:
    name: db
    external: true
  local:
    name: local
    external: true