services:
  web:
    container_name: front
    image: "registry.gitlab.com/i2dru/front:latest"
    networks:
      - local
    environment:
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
networks:
  local:
    external: true
    name: local
    attachable: true
