services:
  web:
    container_name: i2d
    image: "registry.gitlab.com/fggnb45598/i2d:latest"
    ports:
      - "9101:3000"
    environment:
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
networks:
  default:
    external:
      name: local
