services:
  web:
    container_name: i2d
    image: "registry.gitlab.com/fggnb45598/i2d:latest"
    ports:
      - "9101:3000"
networks:
  local:
    external: true
    name: local
    attachable: true
