services:
  web:
    container_name: front
    image: "registry.gitlab.com/i2dru/front:latest"
    environment:
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
networks:
  default:
    external:
      name: local
