version: '3'

services:
  web:
    container_name: nginx
    image: "docker.pkg.github.com/dschek/nginx/nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - local
      - nginx    
    restart: always
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    # depends_on:
    #   - certbot
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - web
    command: certonly --agree-tos --no-eff-email --force-renewal -d tydi.ru -d www.tydi.ru -d restcms.ru -d www.restcms.ru
    
networks:
  nginx:
    name: nginx
  local:        
    name: local   
    external: true       
