version: '3'

services:
  web:
    container_name: nginx
    image: "docker.pkg.github.com/dschek/nginx/nginx:latest"
    ports:
      - "80:80"
      - "443:443"
networks:
  nginx:
    name: nginx
  local:        
    name: local   
    external: true       