version: '3'

services:
  web:
    container_name: nginx
    image: "docker.pkg.github.com/dschek/nginx/nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - local
      - nginx    
    restart: always
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/usr/share/nginx/html
  certbot1:
    image: certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - web
    command: >
      certonly --webroot --webroot-path=/var/www/html --email fggnb45598@gmail.com --agree-tos --no-eff-email --force-renewal -d crystalapp.ru -d www.crystalapp.ru 
  certbot2:
    image: certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - certbot1
    command: >
      certonly --webroot --webroot-path=/var/www/html --email fggnb45598@gmail.com --agree-tos --no-eff-email --force-renewal -d restcms.ru -d www.restcms.ru
  certbot3:
    image: certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - certbot2
    command: >
      certonly --webroot --webroot-path=/var/www/html --email fggnb45598@gmail.com --agree-tos --no-eff-email --force-renewal -d tydi.ru -d www.tydi.ru
# staging
volumes:
  certbot-etc:
  certbot-var:
  web-root:
networks:
  nginx:
    name: nginx
  local:        
    name: local   
    external: true       
