version: '3'

services:
  web:
    container_name: nginx
    image: "docker.pkg.github.com/dschek/nginx/nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - local
      - nginx    
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - web
    # command: certonly --agree-tos --no-eff-email --force-renewal -d tydi.ru -d www.tydi.ru
    
networks:
  nginx:
    name: nginx
  local:        
    name: local   
    external: true       
