version: '3'

services:
  web:
    container_name: nginx
    image: "docker.pkg.github.com/dschek/nginx/nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - local
      - nginx    
    restart: always
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/usr/share/nginx/html
  certbot1:
    image: certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - web
    command: ./certbootStart.sh
# staging
volumes:
  certbot-etc:
  certbot-var:
  web-root:
networks:
  nginx:
    name: nginx
  local:        
    name: local   
    external: true       
