version: '3'

services:
  web:
    container_name: nginx
    image: "docker.pkg.github.com/dschek/nginx/nginx:latest"
    ports:
      - "81:81"
      - "82:82"
      - "83:83"
    networks:
      - local
      - nginx    
    restart: always
    # volumes:
    #   - certbot-etc:/etc/letsencrypt
    #   - certbot-var:/var/lib/letsencrypt
    #   - web-root:/usr/share/nginx/html
#   certbot:
#     image: "ghcr.io/dschek/certboot/certboot:latest"
#     # image: certbot/certbot:latest
#     volumes:
#       - certbot-etc:/etc/letsencrypt
#       - certbot-var:/var/lib/letsencrypt
#       - web-root:/var/www/html
#     depends_on:
#       - web
# # staging
# volumes:
#   certbot-etc:
#   certbot-var:
#   web-root:
networks:
  nginx:
    name: nginx
  local:        
    name: local   
    external: true       
