version: '3.8'

services:
  web:
    container_name: mrcod_tunnel
    image: "registry.gitlab.com/mrcod/tunnel"
    ports:
      - "8380:80"
    networks:
      - local
      - mysql
    environment:
      - DBPORT=$DBPORT
      - DBHOST=$DBHOST
      - DBNAME=$DBNAME
      - DBUSERNAME=$DBUSERNAME
      - DBPASSWORD=$DBPASSWORD
      - PORT=$PORT
networks:
  mysql:
    name: mysql
    external: true
  local:        
    name: local   
    external: true     
