services:
  web:
    container_name: mrcod_tunnel
    image: "registry.gitlab.com/mrcod/tunnel"
    ports:
      - "8380:8380"
      - "50000:50000"
      - "50001:50001"
      - "50002:50002"
      - "50003:50003"
      - "50004:50004"
      - "50005:50005"
      - "50006:50006"
    networks:
      - local
      - mysql
    environment:
      - PORT=$PORT
      - BD_URL=$BD_URL
      - BD_USERNAME=$BD_USERNAME
      - BD_PASSWORD=$BD_PASSWORD
      - SECRET_KEY=$SECRET_KEY
networks:
  mysql:
    name: mysql
    external: true
  local:
    name: local
    external: true     
