version: '3'

services:
  web:
    image: "registry.gitlab.com/fggnb45598/crystal:latest"
    container_name: crystal
    ports:
      - "3001:3001"
    networks:
      - local
      - mongodb
      - email
networks:
  mongodb:
    name: mongodb
    external: true
  email:
    name: email
    external: true
  local:        
    name: local   
    external: true   
