version: '3'

services:
  web:
    image: "ghcr.io/dschek/crystal/crystal:latest"
    container_name: crystal
    ports:
      - "9201:3001"
    networks:
      - local
      - mongodb
      - email
networks:
  mongodb:
    name: mongodb
    external: true
  email:
    name: email
    external: true
  local:        
    name: local   
    external: true   
